Yorku\JuturnaBundle\Entity\Content:
    type: entity
    table: category_contents
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        title:
            type: string
            length: 230
            fixed: false
            nullable: false
            column: title
        detail:
            type: text
            nullable: true
            column: detail
        layerId: 
            type: guid
            unsigned: false
            nullable: false  
            column: layer_id
        categoryId: 
            type: guid
            unsigned: false
            nullable: false  
            column: category_id            
        position: 
            type: integer
            unsigned: false
            nullable: true  
            column: position
        citation:
            type: string
            length: 230
            fixed: false
            nullable: true
            column: citation            
        citationLink:
            type: string
            length: 230
            fixed: false
            nullable: true
            column: citation_link
        description:
            type: text
            nullable: true
            column: description
        tags:
            type: array
            nullable: true
            column: tags
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update    
    oneToMany:
        contentdetails:
            targetEntity: Yorku\JuturnaBundle\Entity\ContentDetail
            mappedBy: categorycontent             
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        contentCategory:
            targetEntity: ContentCategory
            cascade: {  }
            inversedBy: contents
            joinColumns:
              contentcategory_id:
                referencedColumnName: id
        layer:
            targetEntity: Map2u\CoreBundle\Entity\Layer 
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
              layer_id:
                referencedColumnName: id
    manyToMany:                 
       layers:
         targetEntity: Map2u\CoreBundle\Entity\Layer
         inversedBy: {}
         orderBy:
             name: ASC
         joinTable:
           name: categorycontent_layers
           joinColumns:
             categorycontent_id:
               referencedColumnName: id
           inverseJoinColumns:
             layer_id:
               referencedColumnName: id                       
    lifecycleCallbacks: {  }
