Yorku\JuturnaBundle\Entity\EcoSystemService:
    type: entity
    table: eco_system_service
    
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        name:
            type: string
            length: 255
            nullable: false
            column: name
    manyToMany:
        indicatorbenefits:
          targetEntity: IndicatorBenefit
          mappedBy: ecosystemservices  

    lifecycleCallbacks: {  }
