Yorku\JuturnaBundle\Entity\FeatureContents:
    type: entity
    table: feature_contents
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        name:
            type: string
            length: 230
            fixed: false
            nullable: false
            column: name
        report:
            type: text
            nullable: true
            column: report
        reportLink:
            type: string
            length: 230
            fixed: false
            nullable: true
            column: report_link
        featureId:
            type: integer
            fixed: false
            nullable: true
            column: feature_id
        layerType:
            type: string
            length: 130
            fixed: false
            nullable: true
            column: layer_type
        layerId:
            type: integer
            fixed: false
            nullable: true
            column: layer_id
        layerName:
            type: string
            length: 130
            fixed: false
            nullable: true
            column: layer_name
        description:
            type: text
            nullable: true
            column: description
        tags:
            type: array
            nullable: true
            column: tags
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update     
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
