Yorku\JuturnaBundle\Entity\HomepageImage:
    type: entity
    table: homepage_image
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: title
        image:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: image            
        introduce:
            type: string
            length: 500
            fixed: false
            nullable: false
            column: introduce
        altText:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: alt_text                 
        url:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: url
        published:
            type: boolean
            nullable: true
            column: published
        active:
            type: boolean
            nullable: true
            column: active
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        description:
            type: text
            nullable: true
    manyToOne:
        contentCategory:
            targetEntity: Yorku\JuturnaBundle\Entity\ContentCategory
            cascade: {  }
            mappedBy: null
            joinColumns:
                contentcategory_id:
                    referencedColumnName: id
            orphanRemoval: true                        
        contentSubcategory:
            targetEntity: Yorku\JuturnaBundle\Entity\ContentCategory
            cascade: {  }
            mappedBy: null
            joinColumns:
                contentsubcategory_id:
                    referencedColumnName: id
            orphanRemoval: true                        
    lifecycleCallbacks: {  }
