Yorku\JuturnaBundle\Entity\HomepageFlash:
    type: entity
    table: homepage_flashs
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: title
        titleMargin:
            type: integer
            unsigned: false
            nullable: true
            column: title_margin
            options:
                default:
                    0
        alignLeft:
            type: boolean
            nullable: true
            column: align_left
            options:
                default: true                
        introduce:
            type: string
            length: 500
            fixed: false
            nullable: false
            column: introduce
        altText:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: alt_text            
        image:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: image            
        url:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: url
        published:
            type: boolean
            nullable: true
            column: published
        active:
            type: boolean
            nullable: true
            column: active
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        description:
            type: text
            nullable: true
    manyToOne:
        contentCategory:
            targetEntity: Yorku\JuturnaBundle\Entity\ContentCategory
            cascade: {  }
            mappedBy: null
            joinColumns:
                contentcategory_id:
                    referencedColumnName: id
            orphanRemoval: true                        
        contentSubcategory:
            targetEntity: Yorku\JuturnaBundle\Entity\ContentCategory
            cascade: {  }
            mappedBy: null
            joinColumns:
                contentsubcategory_id:
                    referencedColumnName: id
            orphanRemoval: true                                
    lifecycleCallbacks: {  }
