Yorku\JuturnaBundle\Entity\IndicatorReference:
    type: entity
    table: indicator_reference

    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        name:
            type: string
            length: 250
            nullable: false
            column: name
        reference:
            type: string
            length: 512
            nullable: false
            column: reference
        website:
            type: string
            length: 512
            nullable: true
            column: website
    manyToMany:                 
       indicatorbenefits:
         targetEntity: IndicatorBenefit
         mappedBy: indicatorreferences
       additional_indicatorbenefits:
         targetEntity: IndicatorBenefit
         mappedBy: additionalreferences
       otherlinks_indicatorbenefits:
         targetEntity: IndicatorBenefit
         mappedBy: otherlinks
   
    lifecycleCallbacks: {  }
