Yorku\JuturnaBundle\Entity\IndicatorBenefit:
    type: entity
    table: indicator_benefit

    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        title:
            type: string
            length: 255
            nullable: true
            column: title
        benefitName:
            type: string
            length: 255
            nullable: false
            column: benefit_name
        abstract:
            type: string
            length: 2500
            nullable: true
            column: abstract
        briefReport:
            type: text
            nullable: true
            column: brief_report

        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    manyToOne:
        indicator:
            targetEntity: Indicator
            cascade: {  }
            mappedBy: null
            inversedBy: indicatorbenefits
            joinColumns:
                indicator_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:                 
       ecosystemservices:
         targetEntity: EcoSystemService
         inversedBy: indicatorbenefits
         joinTable:
           name: ecosystemservice_indicatorbenefits
           joinColumns:
             indicatorbenefit_id:
               referencedColumnName: id
           inverseJoinColumns:
             ecosystemservice_id:
               referencedColumnName: id                 
       humanwellbeingedomains:
         targetEntity: HumanWellBeingDomain
         inversedBy: indicatorbenefits
         joinTable:
           name: humanwellbeingdomain_indicatorbenefits
           joinColumns:
             indicatorbenefit_id:
               referencedColumnName: id
           inverseJoinColumns:
             humanwellbeingedomain_id:
               referencedColumnName: id   
       indicatorreferences:
          targetEntity: IndicatorReference
          inversedBy: indicatorbenefits
          joinTable:
           name: indicatorreference_indicatorbenefits
           joinColumns:
             indicatorbenefit_id:
               referencedColumnName: id
           inverseJoinColumns:
             indicatorreference_id:
               referencedColumnName: id   
       additionalreferences:
          targetEntity: IndicatorReference
          inversedBy: additional_indicatorbenefits
          joinTable:
           name: additionalreference_indicatorbenefits
           joinColumns:
             indicatorbenefit_id:
               referencedColumnName: id
           inverseJoinColumns:
             additionalreference_id:
               referencedColumnName: id                  
       otherlinks:
          targetEntity: IndicatorReference
          inversedBy: otherlinks_indicatorbenefits
          joinTable:
           name: otherlinks_indicatorbenefits
           joinColumns:
             otherlinks_id:
               referencedColumnName: id
           inverseJoinColumns:
             indicatorreference_id:
               referencedColumnName: id                  
       indicatorbenefitimages:
          targetEntity: IndicatorBenefitImage
          inversedBy: indicatorbenefits
          joinTable:
           name: indicatorbenefitimage_indicatorbenefits
           joinColumns:
             indicatorbenefit_id:
               referencedColumnName: id
           inverseJoinColumns:
             indicatorbenefitimage_id:
               referencedColumnName: id          
       symbolizedLayers:
          targetEntity: Map2u\CoreBundle\Entity\SymbolizedLayer
          orderBy: { 'seq': 'ASC' }
          joinTable:
           name: indicatorbenefits_symbolizedlayers
           joinColumns:
             indicatorbenefit_id:
               referencedColumnName: id
           inverseJoinColumns:
             maplayer_id:
               referencedColumnName: id                         
#       clusterlayers:
#          targetEntity: Map2u\CoreBundle\Entity\LeafletClusterLayer
#          orderBy: { 'seq': 'ASC' }
#          joinTable:
#           name: indicatorbenefits_clusterlayers
#           joinColumns:
#             clusterlayer_id:
#               referencedColumnName: id
#           inverseJoinColumns:
#             indicatorbenefit_id:
#               referencedColumnName: id       
#       geoserverlayers:
#          targetEntity: Map2u\CoreBundle\Entity\GeoServerLayer
#          orderBy: { 'seq': 'ASC' }
#          joinTable:
#           name: indicatorbenefits_geoserverlayers
#           joinColumns:
#             geoserverlayer_id:
#               referencedColumnName: id
#           inverseJoinColumns:
#             indicatorbenefit_id:
#               referencedColumnName: id                      
    lifecycleCallbacks: {  }
