Yorku\JuturnaBundle\Entity\Story:
    type: entity
    table: yorku_juturna__stories
    gedmo:
        translation:
            locale: locale
            # using specific personal translation class:
            entity: Yorku\JuturnaBundle\Entity\StoryTranslation     
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID

    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        storyType:
            targetEntity: Map2u\CoreBundle\Entity\StoryType
            cascade: {  }
            inversedBy: {}
            joinColumns:
                storytype_id:
                    referencedColumnName: id
            orphanRemoval: false  
    lifecycleCallbacks: {  }
