Yorku\JuturnaBundle\Entity\Story:
    type: entity
    table: stories

    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        storyName:
            type: string
            length: 255
            nullable: false
            column: story_name
        summary:
            type: string
            length: 255
            nullable: true
            column: summary
        type:
            type: string
            length: 255
            nullable: true
            column: type
        radius:
            type: float
            nullable: true
            column: radius
        imageFile:
            type: string
            length: 250
            nullable: true
            column: image_file
        altText:
            type: string
            length: 500
            fixed: false
            nullable: true
            column: alt_text                 
        storyFile:
            type: string
            length: 255
            nullable: true
            column: story_file
        storyFileType:
            type: string
            length: 255
            nullable: true
            column: story_filetype     
        storyText:
            type: text
            nullable: true
            column: story_text                 
        email:
            type: string
            length: 255
            nullable: true
            column: email
        theGeom:
            type: geometry
            nullable: true
            requireSQLConversion: true
            column: the_geom
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
 
    lifecycleCallbacks: {  }
