Yorku\JuturnaBundle\Entity\UserLayerSeq:
    type: entity
    table: userlayerseq

    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        name:
            type: string
            length: 255
            nullable: false
            column: name
            
        positions:
            type: text
            nullable: true
            column: positions
            
        description:
            type: text
            nullable: true
            column: description

        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
 
    lifecycleCallbacks: {  }
