security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        map2u_hwi_provider:
            id: app_user.oauth_user_provider

        fos_userbundle:
            id: fos_user.user_provider.username_email
#        in_memory:
#            memory:
#                users:
#                    user:  { password: %userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: %adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
#        secured_area:
#            anonymous: ~
#            oauth:
#                resource_owners:
#                    facebook:           "/secured/login/check-facebook"
#                    google:             "/secured/login/check-google"
##                    my_custom_provider: "/login/check-custom"
##                    my_github:          "/login/check-github"
#                login_path:        /secured/login
#                use_forward:       false
#                failure_path:      /secured/login
#
#                oauth_user_provider:
#                    service: app_user.oauth_user_provider #hwi_oauth.user.provider.entity #//map2u.oauth_aware.user_provider.service        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        admin:
#            pattern:      /admin(.*)
#            form_login:
#                provider:       fos_userbundle
#                login_path:     /admin/login
#                use_forward:    false
#                check_path:     /admin/login_check
#                failure_path:   null
#            logout:
#                path:           /admin/logout
#            anonymous:    true
#        # -> end custom configuration
# 
        main:
            pattern:  .*
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                use_forward:    false
                login_path: fos_user_security_login
                csrf_provider: form.csrf_provider
                success_handler: map2u_core.authentication.success_handler
                failure_handler: map2u_core.authentication.failure_handler
                # no this item               csrf_protection:  false
            logout: 
                path: fos_user_security_logout
           #     handlers: ['sonata.page.cms_manager_selector']
                target: /
#                target: index          
            anonymous:    true
            oauth:
                resource_owners:
                    facebook:           "/secured/login/check-facebook"
                    google:             "/secured/login/check-google"
                    yahoo:              "/secured/login/check-yahoo"
                    twitter:            "/secured/login/check-twitter"
                    qq:                 "/secured/login/check-qq"
                oauth_user_provider:
                    service: app_user.oauth_user_provider 
                provider:   fos_userbundle
                check_path: fos_user_security_check
                use_forward:    false
                login_path: /connect 

                    
    acl:
        connection: default

    access_control:
       # - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
