<?php

/**
<<<<<<< HEAD
 * <copyright>
 * This file/program is free and open source software released under the GNU General Public
 * License version 3, and is distributed WITHOUT ANY WARRANTY. A copy of the GNU General
 * Public Licence is available at http://www.gnu.org/licenses
 * </copyright>
 *
 * <author>Shuilin (Joseph) Zhao</author>
 * <company>SpEAR Lab, Faculty of Environmental Studies, York University
 * <email>zhaoshuilin2004@yahoo.ca</email>
 * <date>created at 2014/01/06</date>
 * <date>last updated at 2015/03/11</date>
 * <summary>This is the extend of Sonata\NewsBundle\Entity\BaseComment entity</summary>
 * <purpose>for entity extend based on Sonata\NewsBundle\Entity\BaseComment</purpose>
=======
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
>>>>>>> update map2u bundles
 */

namespace Application\Sonata\NewsBundle\Entity;

use Sonata\NewsBundle\Entity\BaseComment as BaseComment;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
<<<<<<< HEAD
class Comment extends BaseComment {

=======
class Comment extends BaseComment
{
>>>>>>> update map2u bundles
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
<<<<<<< HEAD
    public function getId() {
        return $this->id;
    }

=======
    public function getId()
    {
        return $this->id;
    }
>>>>>>> update map2u bundles
    /**
     * @var integer $id
     */
    protected $post_id;

    /**
     * Get post_id
     *
     * @return integer $post_id
     */
<<<<<<< HEAD
    public function getPostId() {
        return $this->post_id;
    }

=======
    public function getPostId()
    {
        return $this->post_id;
    }
>>>>>>> update map2u bundles
    /**
     * set post_id
     *
     * @return Comment
     */
<<<<<<< HEAD
    public function setPostId($post_id) {
        $this->post_id = $post_id;
        return $this;
    }

}
=======
    public function setPostId($post_id)
    {
      $this->post_id=$post_id;
        return $this;
    }
}
>>>>>>> update map2u bundles
